Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using BookTrail.DataAccess.Data;
using BookTrail.Models;
using BookTrail.DataAccess.Repository.IRepository;

namespace BookTrailWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Category> categories = _unitOfWork.Category.GetAll().ToList();
            return View(categories);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            //applying custom validation
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Category Name and Display Order can not be same");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                TempData["success"] = "Category created successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id is null or 0)
            {
                return NotFound();
            }
            Category? category = _unitOfWork.Category.Get(u => u.CategoryId == id);
            //Category? category1 = _context.Categories.FirstOrDefault(u=>u.CategoryId == id);
            //Category? category2 = _context.Categories.Where(u=>u.CategoryId == id).FirstOrDefault();

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                TempData["success"] = "Category updated successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id is null or 0)
            {
                return NotFound();
            }
            Category? category = _unitOfWork.Category.Get(u => u.CategoryId == id);
            //Category? category1 = _context.Categories.FirstOrDefault(u=>u.CategoryId == id);
            //Category? category2 = _context.Categories.Where(u=>u.CategoryId == id).FirstOrDefault();

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Category? category = _unitOfWork.Category.Get(u => u.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            _unitOfWork.Category.Remove(category);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted successfully!";
            return RedirectToAction("Index");
        }
    }
}

Areas/Customer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using BookTrail.Models;
using System.Diagnostics;

namespace BookTrailWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MilkyWeb.Data;
using MilkyWeb.Models;

namespace MilkyWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext context) { 
            _context = context;
        }
        public IActionResult Index()
        {
            List<Category> categories = _context.Categories.ToList();
            return View(categories);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            //applying custom validation
            if(category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Category Name and Display Order can not be same");
            }
            if (ModelState.IsValid)
            {
                _context.Categories.Add(category);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id is null or 0)
            {
                return NotFound();
            }
            Category? category = _context.Categories.Find(id);
            //Category? category1 = _context.Categories.FirstOrDefault(u=>u.CategoryId == id);
            //Category? category2 = _context.Categories.Where(u=>u.CategoryId == id).FirstOrDefault();

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Categories.Update(category);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id is null or 0)
            {
                return NotFound();
            }
            Category? category = _context.Categories.Find(id);
            //Category? category1 = _context.Categories.FirstOrDefault(u=>u.CategoryId == id);
            //Category? category2 = _context.Categories.Where(u=>u.CategoryId == id).FirstOrDefault();

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int ? id)
        {
            Category? category = _context.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }

            _context.Categories.Remove(category);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MilkyWeb.Models;
using System.Diagnostics;

namespace MilkyWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Areas/Admin/Views/Category/Create.cshtml
@model Category

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h1 class="text-primary">Create Category</h1>
            <hr />
        </div>
        @*To Show all errors summary *@
        <div asp-validation-summary="ModelOnly"></div>
        <div class="mb-3 row p-0">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-0">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" />
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Category" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@* Adding client side validation (we need to use JS) *@
@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial"/>
    }
}

Areas/Admin/Views/Category/Delete.cshtml
@model Category

<form method="post">
    <input asp-for="CategoryId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h1 class="text-primary">Delete Category</h1>
            <hr />
        </div>
        <div class="mb-3 row p-0">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-0">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" disabled class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Category" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

Areas/Admin/Views/Category/Edit.cshtml
@model Category

<form method="post">
    <input asp-for="CategoryId" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h1 class="text-primary">Update Category</h1>
            <hr />
        </div>
        @*To Show all errors summary *@
        <div asp-validation-summary="ModelOnly"></div>
        <div class="mb-3 row p-0">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-0">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" class="form-control" />
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Category" asp-action="Index" class="btn btn-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@* Adding client side validation (we need to use JS) *@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Areas/Admin/Views/Category/Index.cshtml
@model List<Category>
@* @if(TempData["success"] != null)
{
        <h1>@TempData["success"]</h1>
} *@

<div class="container" >
        <div class="row pt-4 pb-2">
            <div class="col-6">
                <h1>Category List</h1>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-patch-plus"></i> Create New Category
                </a>
            </div>
        </div>
<table class="table table-bordered table-striped">
    <thead>
        <th>
            Category Name
        </th>
        <th>
            Display Order
        </th>
        <th></th>
    </thead>
    <tbody>
        @foreach(var obj in Model.OrderBy(u=>u.DisplayOrder))
        {
            <tr>
                <td>@obj.Name</td>
                <td>@obj.DisplayOrder</td>
                <td align="right">
                    <div class="w-75  btn-group" role="group">
                        <a asp-controller="Category" asp-action="Edit" asp-route-id="@obj.CategoryId" class="btn btn-primary">
                                <i class="bi bi-pencil-square"></i> Edit
                        </a>
                        <a asp-controller="Category" asp-action="Delete" asp-route-id="@obj.CategoryId" class="btn btn-danger">
                                <i class="bi bi-trash3-fill"></i> Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table> 
</div>

Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Category/Index.cshtml
@model List<Category>

    <div class="container" >
        <div class="row pt-4 pb-2">
            <div class="col-6">
                <h1>Category List</h1>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-patch-plus"></i> Create New Category
                </a>
            </div>
        </div>
<table class="table table-bordered table-striped">
    <thead>
        <th>
            Category Name
        </th>
        <th>
            Display Order
        </th>
        <th></th>
    </thead>
    <tbody>
        @foreach(var obj in Model.OrderBy(u=>u.DisplayOrder))
        {
            <tr>
                <td>@obj.Name</td>
                <td>@obj.DisplayOrder</td>
                <td align="right">
                    <div class="w-75  btn-group" role="group">
                        <a asp-controller="Category" asp-action="Edit" asp-route-id="@obj.CategoryId" class="btn btn-primary">
                                <i class="bi bi-pencil-square"></i> Edit
                        </a>
                        <a asp-controller="Category" asp-action="Delete" asp-route-id="@obj.CategoryId" class="btn btn-danger">
                                <i class="bi bi-trash3-fill"></i> Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table> 
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookTrailWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookTrailWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookTrailWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bg-primary footer text-muted">
        <div class="text-center text-white">
            Made with D<i class="bi bi-heart-fill"></i>S
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib//jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib//jquery/dist/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}